/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eleicoesjava.View;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class JanelaPartido extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPartido
     */
    public JanelaPartido() {
        initComponents();
        configurarCorDigitacaoTextoTodosCampos();
        cardLayout = (CardLayout) MAIN.getLayout(); 
    }
    private void configurarCorDigitacaoTextoTodosCampos() {
    configurarCorRecursivo(getContentPane());
}

private void configurarCorRecursivo(java.awt.Container container) {
    for (java.awt.Component c : container.getComponents()) {
        if (c instanceof javax.swing.JTextField txt) {

            javax.swing.Timer t = new javax.swing.Timer(800, e -> {
                txt.setForeground(Color.BLACK);
                txt.setFont(new Font("Segoe UI Semibold",Font.PLAIN,15));// volta à cor normal ao parar
            });
            t.setRepeats(false);

            txt.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                @Override
                public void insertUpdate(javax.swing.event.DocumentEvent e) { aoDigitar(); }
                @Override
                public void removeUpdate(javax.swing.event.DocumentEvent e) { aoDigitar(); }
                @Override
                public void changedUpdate(javax.swing.event.DocumentEvent e) { aoDigitar(); }

                private void aoDigitar() {
                    txt.setForeground(new Color(24,100,90)); // cor do texto enquanto digita
                    txt.setFont(new Font("Rockwell",Font.PLAIN,15));
                    t.restart();
                }
            });

        } else if (c instanceof java.awt.Container childContainer) {
            // percorre dentro dos paineis e layouts
            configurarCorRecursivo(childContainer);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MAIN.setBackground(new java.awt.Color(170, 108, 58));
        MAIN.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MAIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MAIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
try {
            UIManager.setLookAndFeel( new FlatArcOrangeIJTheme());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Look and feel nao encontrado","Look and fell",1);
        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPartido().setVisible(true);
            }
        });
    }

    
     public JPanel getContentPanel() {
        return MAIN; // Retorna o JPanel que contém o CardLayout
    }
        
        public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }
        
        public void setJanelaEleitor(JanelaPartido janelaPartidor) {
        this.janelaPartidor = janelaPartidor;
    }


     public void mostrarTela(String nomeTela) {
        cardLayout.show(MAIN, nomeTela);
    }

        private CardLayout cardLayout;
     private   MenuPrincipal menuPrincipal;
     JanelaPartido janelaPartidor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MAIN;
    // End of variables declaration//GEN-END:variables
}
