/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eleicoesjava.View;

import Model.Dao.FuncionarioDao;
import Model.Dao.FuncionarioDao;
import eleicoesjava.Modelo.Funcionario;
import eleicoesjava.Modelo.Funcionario;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class tabelaFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form TabelaFuncionario
     */
    public tabelaFuncionarios() {
        initComponents();
        lerTabela();
        cardLayout = (CardLayout) MAIN.getLayout(); 
    }

    public void lerTabela () {
        DefaultTableModel modelo = (DefaultTableModel) tbFuncionario.getModel();
        modelo.setNumRows(0);
        FuncionarioDao dao = new FuncionarioDao();
        for (Funcionario f : dao.listarTabela()) {

            modelo.addRow(new Object[]{
               f.getId(),
                f.getNome(),
                f.getBI(),
                f.getDataNasc(),
                f.getGenero(),
                f.getTipoFuncionario(),});


        }

    }

    public void lerBusca(String termo) {
        DefaultTableModel modelo = (DefaultTableModel) tbFuncionario.getModel();
        modelo.setNumRows(0);
        FuncionarioDao dao = new FuncionarioDao();
        for (Funcionario f : dao.busca(termo)) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getBI(),
                f.getDataNasc(),
                f.getGenero(),
                f.getTipoFuncionario(),});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN = new javax.swing.JPanel();
        paneltbEleitor1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFuncionario = new javax.swing.JTable();
        txtBusca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBusca1 = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnListar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MAIN.setBackground(new java.awt.Color(170, 108, 58));
        MAIN.setLayout(new java.awt.CardLayout());

        paneltbEleitor1.setBackground(new java.awt.Color(170, 108, 58));

        tbFuncionario.setBackground(new java.awt.Color(204, 190, 176));
        tbFuncionario.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tbFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "B.I", "Nascimento", "Genero", "Tipo Funcionario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbFuncionario);

        txtBusca.setBackground(new java.awt.Color(255, 255, 153));
        txtBusca.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtBusca.setCaretColor(new java.awt.Color(255, 102, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Swis721 BT", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Pesquisar (Nome/B.I)");

        btnBusca1.setBackground(javax.swing.UIManager.getDefaults().getColor("OptionPane.warningDialog.titlePane.shadow"));
        btnBusca1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnBusca1.setForeground(new java.awt.Color(255, 255, 153));
        btnBusca1.setText("Buscar");
        btnBusca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusca1ActionPerformed(evt);
            }
        });

        btnVoltar1.setBackground(javax.swing.UIManager.getDefaults().getColor("OptionPane.warningDialog.titlePane.shadow"));
        btnVoltar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnVoltar1.setForeground(new java.awt.Color(255, 255, 153));
        btnVoltar1.setText("Voltar");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        btnActualizar1.setBackground(javax.swing.UIManager.getDefaults().getColor("OptionPane.warningDialog.titlePane.shadow"));
        btnActualizar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnActualizar1.setForeground(new java.awt.Color(255, 255, 153));
        btnActualizar1.setText("Actualizar");

        btnEliminar1.setBackground(javax.swing.UIManager.getDefaults().getColor("OptionPane.warningDialog.titlePane.shadow"));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 153));
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnListar1.setBackground(javax.swing.UIManager.getDefaults().getColor("OptionPane.warningDialog.titlePane.shadow"));
        btnListar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnListar1.setForeground(new java.awt.Color(255, 255, 153));
        btnListar1.setText("Listar");
        btnListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Tabela de Funcionarios");

        javax.swing.GroupLayout paneltbEleitor1Layout = new javax.swing.GroupLayout(paneltbEleitor1);
        paneltbEleitor1.setLayout(paneltbEleitor1Layout);
        paneltbEleitor1Layout.setHorizontalGroup(
            paneltbEleitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltbEleitor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneltbEleitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneltbEleitor1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltbEleitor1Layout.createSequentialGroup()
                        .addGap(0, 148, Short.MAX_VALUE)
                        .addGroup(paneltbEleitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltbEleitor1Layout.createSequentialGroup()
                                .addComponent(btnListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltbEleitor1Layout.createSequentialGroup()
                                .addGroup(paneltbEleitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(paneltbEleitor1Layout.createSequentialGroup()
                                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltbEleitor1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(311, 311, 311))
        );
        paneltbEleitor1Layout.setVerticalGroup(
            paneltbEleitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltbEleitor1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addGroup(paneltbEleitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneltbEleitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        MAIN.add(paneltbEleitor1, "CardTbFuncionarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusca1ActionPerformed
        // TODO add your handling code here:
        lerBusca(txtBusca.getText());
    }//GEN-LAST:event_btnBusca1ActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        // TODO add your handling code here:
        menuPrincipal.mostrarTela("CardFuncionario");
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
          if (tbFuncionario.getSelectedRow() != -1) {
            Funcionario f = new Funcionario();
            FuncionarioDao dao = new FuncionarioDao();
            
            f.setId((int) tbFuncionario.getValueAt(tbFuncionario.getSelectedRow(), 0));

            dao.eliminar(f);

            lerTabela();
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um eleitor para Excluir");
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar1ActionPerformed
        // TODO add your handling code here:
        lerTabela();
    }//GEN-LAST:event_btnListar1ActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabelaFuncionarios().setVisible(true);
            }
        });
    }

     public JPanel getContentPanel() {
        return MAIN; // Retorna o JPanel que contém o CardLayout
    }
        
        public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }
        
        public void setTabelaFuncionarios(tabelaFuncionarios TabelaFuncionarios) {
        this.TabelaFuncionarios = TabelaFuncionarios;
    }


     public void mostrarTela(String nomeTela) {
        cardLayout.show(MAIN, nomeTela);
    }

        private CardLayout cardLayout;
     private   MenuPrincipal menuPrincipal;
     tabelaFuncionarios TabelaFuncionarios;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MAIN;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnBusca1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnListar1;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel paneltbEleitor1;
    private javax.swing.JTable tbFuncionario;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
